module.exports = {
  theme: {
    fontFamily: {
      header: ['josefin-sans-light'],
      body: ['lato-regular'],
      josefinSans: ['josefin-sans-regular'],
      josefinSansBold: ['josefin-sans-bold'],
      josefinSansBoldItalic: ['josefin-sans-bold-italic'],
      josefinSansItalic: ['josefin-sans-italic'],
      josefinSansLight: ['josefin-sans-light'],
      josefinSansLightItalic: ['josefin-sans-light-italic'],
      josefinSansSemibold: ['josefin-sans-semi-bold'],
      josefinSansSemiboldItalic: ['josefin-sans-semi-bold-italic'],
      josefinSansThin: ['josefin-sans-thin'],
      josefinSansThinItalic: ['josefin-sans-thin-italic'],
      lato: ['lato-regular'],
      latoBold: ['lato-bold'],
      latoBoldItalic: ['lato-bold-italic'],
      latoHairline: ['lato-hairline'],
      latoHairlineItalic: ['lato-hairline-italic'],
      latoHeavy: ['lato-heavy'],
      latoHeavyItalic: ['lato-heavy-italic'],
      latoItalic: ['lato-italic'],
      latoLight: ['lato-light'],
      latoLightItalic: ['lato-light-italic'],
      latoMedium: ['lato-medium'],
      latoMediumItalic: ['lato-medium-italic'],
      latoSemibold: ['lato-semibold'],
      latoSemiboldItalic: ['lato-semibold-italic'],
      latoThin: ['lato-thin'],
      latoThinItalic: ['lato-thin-italic'],
      latoRegular: ['lato-regular'],
    },
    colors: {
      transparent: 'transparent',

      black: '#000',
      white: '#fff',
      primary: '#fff',
      // primary: '#d1f2f4',
      pendingSlot: '#fef200',
      bookedSlot: '#435B77',
      availableSlot: '#eaf6ff',

      gray: {
        '100': '#FFFFFF',
        '200': '#F8F8F9',
        '300': '#E3E5E7',
        '400': '#CFD1D5',
        '500': '#BABDC3',
        '600': '#95979C',
        '700': '#646B74',
        '800': '#38393A',
        '900': '#424242',
      },
      teal: {
        '100': '#EDF8FA',
        '200': '#CAEBEF',
        '300': '#A7DEE4',
        '400': '#84D0D9',
        '500': '#4FBCC8',
        '600': '#47A9B4',
        '700': '#3F96A0',
        '800': '#37848C',
        '900': '#285E64',
      },
      blue: {
        '100': '#D8DDE3',
        '200': '#9EAAB9',
        '300': '#8A99AA',
        '400': '#3B629A',
        '500': '#344573',
        '600': '#3C5572',
        '700': '#30445B',
        '800': '#2A3B50',
        '900': '#1E2B39',
      },
      mint: {
        '100': '#EFF9F7',
        '200': '#CEECE7',
        '300': '#9DD9D0',
        '400': '#7CCCC0',
        '500': '#5BBFB0',
        '600': '#52AC9E',
        '700': '#49998D',
        '800': '#40867B',
        '900': '#2E6058',
      },
      purple: {
        '500': '#5C70A3',
      },
      yellow: {
        '500': '#FFCB1D',
      },
      royal: {
        '500': '#3B629A',
      },
      red: {
        '500': '#E20606',
      },
    },
    extend: {
      maxWidth: {
        '7xl': '100rem',
      },
    },
  },
  variants: {},
  plugins: [],
};
