/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateTourStopMessage = /* GraphQL */ `
  subscription OnCreateTourStopMessage($tour_stop_id: Int!) {
    onCreateTourStopMessage(tour_stop_id: $tour_stop_id) {
      id
      from_user
      to_user
      message
      tour_stop_id
      created_at
      updated_at
      insert_uuid
      recipient {
        id
        first_name
        last_name
        email_address
        cell_phone
        logo
        brokerage
        realtor_number
        is_agent
        is_test_account
        validated
      }
      sender {
        id
        first_name
        last_name
        email_address
        cell_phone
        logo
        brokerage
        realtor_number
        is_agent
        is_test_account
        validated
      }
    }
  }
`;
export const onCreateTour = /* GraphQL */ `
  subscription OnCreateTour($client_id: Int!) {
    onCreateTour(client_id: $client_id) {
      id
      name
      status
      start_time
      end_time
      custom_start_name
      address_str
      latitude
      longitude
      client_id
      agent_id
      current_tour_stop_id
      current_tour_stop {
        id
        order
        duration
        notify_before
        notify_listing_agent
        notify_seller
        notify_after
        request_sent
        showing_request_required
        next_up_sent
        next_up_sent_by
        have_left_sent
        have_left_sent_by
        est_drive_duration
        est_drive_str
        comments
        client_interested
        start_time
        status
        tour_id
        property_of_interest_id
        last_request_sent_by_user_id
        created_at
        updated_at
        insert_uuid
        is_active
        property_of_interest {
          id
          property_listing_id
          client_id
          status
          notes
          created_at
          updated_at
          property_listing {
            id
            listing_agent_id
            seller_id
            created_by_user_id
            listing_id
            listing_key
            address
            city
            county
            state
            zip
            subdivision_name
            zoning
            latitude
            longitude
            parcel_number
            additional_parcels
            is_custom_listing
            listing_price
            association_fee
            association_fee_frequency
            on_market_date
            bedrooms
            bathrooms
            bathrooms_full
            square_feet
            square_feet_source
            lot_size
            year_built
            property_sub_type
            status
            description
            rented
            in_association
            community_features
            short_term_rental_permit_issued
            elementary_school
            middle_or_junior_school
            high_school
            tax_annual_amount
            tax_year
            tax_lot
            tax_map_number
            potential_tax_liability
            assessment
            senior_community
            appliances
            cooling
            heating
            fireplace_features
            flooring
            interior_features
            rooms
            window_features
            security_features
            architectural_style
            lot_features
            garage
            garage_spaces
            parking_features
            road_surface_types
            view
            horse_property
            new_construction
            last_updated
            source
            originating_system
            accessory_dwelling_unit
            levels
            common_walls
            construction_materials
            basement
            foundation_details
            power_production_type
            roof
            sewer
            water_source
            irrigation_water_rights
            media_url
            is_auto_approve
            showing_request_deadline
            deadline_start_time
            created_at
            updated_at
            insert_uuid
            listing_agent {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
            seller {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
          }
          client {
            id
            first_name
            last_name
            email_address
            cell_phone
            logo
            brokerage
            realtor_number
            is_agent
            is_test_account
            validated
          }
          media_url
          seen_by_client
          active_for_client
          insert_uuid
          client_notes
          client_notes_updated_at
        }
      }
      created_at
      updated_at
      insert_uuid
      client {
        id
        first_name
        last_name
        email_address
        cell_phone
        logo
        brokerage
        realtor_number
        is_agent
        is_test_account
        validated
      }
      stops {
        id
        order
        duration
        notify_before
        notify_listing_agent
        notify_seller
        notify_after
        request_sent
        showing_request_required
        next_up_sent
        next_up_sent_by
        have_left_sent
        have_left_sent_by
        est_drive_duration
        est_drive_str
        comments
        client_interested
        start_time
        status
        tour_id
        property_of_interest_id
        last_request_sent_by_user_id
        created_at
        updated_at
        insert_uuid
        is_active
        property_of_interest {
          id
          property_listing_id
          client_id
          status
          notes
          created_at
          updated_at
          property_listing {
            id
            listing_agent_id
            seller_id
            created_by_user_id
            listing_id
            listing_key
            address
            city
            county
            state
            zip
            subdivision_name
            zoning
            latitude
            longitude
            parcel_number
            additional_parcels
            is_custom_listing
            listing_price
            association_fee
            association_fee_frequency
            on_market_date
            bedrooms
            bathrooms
            bathrooms_full
            square_feet
            square_feet_source
            lot_size
            year_built
            property_sub_type
            status
            description
            rented
            in_association
            community_features
            short_term_rental_permit_issued
            elementary_school
            middle_or_junior_school
            high_school
            tax_annual_amount
            tax_year
            tax_lot
            tax_map_number
            potential_tax_liability
            assessment
            senior_community
            appliances
            cooling
            heating
            fireplace_features
            flooring
            interior_features
            rooms
            window_features
            security_features
            architectural_style
            lot_features
            garage
            garage_spaces
            parking_features
            road_surface_types
            view
            horse_property
            new_construction
            last_updated
            source
            originating_system
            accessory_dwelling_unit
            levels
            common_walls
            construction_materials
            basement
            foundation_details
            power_production_type
            roof
            sewer
            water_source
            irrigation_water_rights
            media_url
            is_auto_approve
            showing_request_deadline
            deadline_start_time
            created_at
            updated_at
            insert_uuid
            listing_agent {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
            seller {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
          }
          client {
            id
            first_name
            last_name
            email_address
            cell_phone
            logo
            brokerage
            realtor_number
            is_agent
            is_test_account
            validated
          }
          media_url
          seen_by_client
          active_for_client
          insert_uuid
          client_notes
          client_notes_updated_at
        }
      }
      seen_by_client
      manually_ordered_showings
      is_behalf_of_buying_agent
    }
  }
`;
export const onTourChange = /* GraphQL */ `
  subscription OnTourChange($client_id: Int!) {
    onTourChange(client_id: $client_id) {
      id
      name
      status
      start_time
      end_time
      custom_start_name
      address_str
      latitude
      longitude
      client_id
      agent_id
      current_tour_stop_id
      current_tour_stop {
        id
        order
        duration
        notify_before
        notify_listing_agent
        notify_seller
        notify_after
        request_sent
        showing_request_required
        next_up_sent
        next_up_sent_by
        have_left_sent
        have_left_sent_by
        est_drive_duration
        est_drive_str
        comments
        client_interested
        start_time
        status
        tour_id
        property_of_interest_id
        last_request_sent_by_user_id
        created_at
        updated_at
        insert_uuid
        is_active
        property_of_interest {
          id
          property_listing_id
          client_id
          status
          notes
          created_at
          updated_at
          property_listing {
            id
            listing_agent_id
            seller_id
            created_by_user_id
            listing_id
            listing_key
            address
            city
            county
            state
            zip
            subdivision_name
            zoning
            latitude
            longitude
            parcel_number
            additional_parcels
            is_custom_listing
            listing_price
            association_fee
            association_fee_frequency
            on_market_date
            bedrooms
            bathrooms
            bathrooms_full
            square_feet
            square_feet_source
            lot_size
            year_built
            property_sub_type
            status
            description
            rented
            in_association
            community_features
            short_term_rental_permit_issued
            elementary_school
            middle_or_junior_school
            high_school
            tax_annual_amount
            tax_year
            tax_lot
            tax_map_number
            potential_tax_liability
            assessment
            senior_community
            appliances
            cooling
            heating
            fireplace_features
            flooring
            interior_features
            rooms
            window_features
            security_features
            architectural_style
            lot_features
            garage
            garage_spaces
            parking_features
            road_surface_types
            view
            horse_property
            new_construction
            last_updated
            source
            originating_system
            accessory_dwelling_unit
            levels
            common_walls
            construction_materials
            basement
            foundation_details
            power_production_type
            roof
            sewer
            water_source
            irrigation_water_rights
            media_url
            is_auto_approve
            showing_request_deadline
            deadline_start_time
            created_at
            updated_at
            insert_uuid
            listing_agent {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
            seller {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
          }
          client {
            id
            first_name
            last_name
            email_address
            cell_phone
            logo
            brokerage
            realtor_number
            is_agent
            is_test_account
            validated
          }
          media_url
          seen_by_client
          active_for_client
          insert_uuid
          client_notes
          client_notes_updated_at
        }
      }
      created_at
      updated_at
      insert_uuid
      client {
        id
        first_name
        last_name
        email_address
        cell_phone
        logo
        brokerage
        realtor_number
        is_agent
        is_test_account
        validated
      }
      stops {
        id
        order
        duration
        notify_before
        notify_listing_agent
        notify_seller
        notify_after
        request_sent
        showing_request_required
        next_up_sent
        next_up_sent_by
        have_left_sent
        have_left_sent_by
        est_drive_duration
        est_drive_str
        comments
        client_interested
        start_time
        status
        tour_id
        property_of_interest_id
        last_request_sent_by_user_id
        created_at
        updated_at
        insert_uuid
        is_active
        property_of_interest {
          id
          property_listing_id
          client_id
          status
          notes
          created_at
          updated_at
          property_listing {
            id
            listing_agent_id
            seller_id
            created_by_user_id
            listing_id
            listing_key
            address
            city
            county
            state
            zip
            subdivision_name
            zoning
            latitude
            longitude
            parcel_number
            additional_parcels
            is_custom_listing
            listing_price
            association_fee
            association_fee_frequency
            on_market_date
            bedrooms
            bathrooms
            bathrooms_full
            square_feet
            square_feet_source
            lot_size
            year_built
            property_sub_type
            status
            description
            rented
            in_association
            community_features
            short_term_rental_permit_issued
            elementary_school
            middle_or_junior_school
            high_school
            tax_annual_amount
            tax_year
            tax_lot
            tax_map_number
            potential_tax_liability
            assessment
            senior_community
            appliances
            cooling
            heating
            fireplace_features
            flooring
            interior_features
            rooms
            window_features
            security_features
            architectural_style
            lot_features
            garage
            garage_spaces
            parking_features
            road_surface_types
            view
            horse_property
            new_construction
            last_updated
            source
            originating_system
            accessory_dwelling_unit
            levels
            common_walls
            construction_materials
            basement
            foundation_details
            power_production_type
            roof
            sewer
            water_source
            irrigation_water_rights
            media_url
            is_auto_approve
            showing_request_deadline
            deadline_start_time
            created_at
            updated_at
            insert_uuid
            listing_agent {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
            seller {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
          }
          client {
            id
            first_name
            last_name
            email_address
            cell_phone
            logo
            brokerage
            realtor_number
            is_agent
            is_test_account
            validated
          }
          media_url
          seen_by_client
          active_for_client
          insert_uuid
          client_notes
          client_notes_updated_at
        }
      }
      seen_by_client
      manually_ordered_showings
      is_behalf_of_buying_agent
    }
  }
`;
export const chatReceiveNewMessage = /* GraphQL */ `
  subscription ChatReceiveNewMessage($receiver_id: Int!) {
    chatReceiveNewMessage(receiver_id: $receiver_id) {
      id
      receiver_id
      chat_id
    }
  }
`;
export const onUpdateTourStopRequestStatus = /* GraphQL */ `
  subscription OnUpdateTourStopRequestStatus($tour_id: Int!) {
    onUpdateTourStopRequestStatus(tour_id: $tour_id) {
      id
      status
      last_request_sent_by_user_id
      showing_request_required
      tour_id
      listing_agent_id
      start_time
    }
  }
`;
export const onUpdateShowingRequestStatus = /* GraphQL */ `
  subscription OnUpdateShowingRequestStatus($listing_agent_id: Int!) {
    onUpdateShowingRequestStatus(listing_agent_id: $listing_agent_id) {
      id
      status
      last_request_sent_by_user_id
      showing_request_required
      tour_id
      listing_agent_id
      start_time
    }
  }
`;
export const onShowingRemoved = /* GraphQL */ `
  subscription OnShowingRemoved($listing_agent_id: Int!) {
    onShowingRemoved(listing_agent_id: $listing_agent_id) {
      id
      listing_agent_id
      is_active
    }
  }
`;
export const onPropertyOfInterestChange = /* GraphQL */ `
  subscription OnPropertyOfInterestChange($client_id: Int!) {
    onPropertyOfInterestChange(client_id: $client_id) {
      id
      property_listing_id
      client_id
      status
      notes
      created_at
      updated_at
      property_listing {
        id
        listing_agent_id
        seller_id
        created_by_user_id
        listing_id
        listing_key
        address
        city
        county
        state
        zip
        subdivision_name
        zoning
        latitude
        longitude
        parcel_number
        additional_parcels
        is_custom_listing
        listing_price
        association_fee
        association_fee_frequency
        on_market_date
        bedrooms
        bathrooms
        bathrooms_full
        square_feet
        square_feet_source
        lot_size
        year_built
        property_sub_type
        status
        description
        rented
        in_association
        community_features
        short_term_rental_permit_issued
        elementary_school
        middle_or_junior_school
        high_school
        tax_annual_amount
        tax_year
        tax_lot
        tax_map_number
        potential_tax_liability
        assessment
        senior_community
        appliances
        cooling
        heating
        fireplace_features
        flooring
        interior_features
        rooms
        window_features
        security_features
        architectural_style
        lot_features
        garage
        garage_spaces
        parking_features
        road_surface_types
        view
        horse_property
        new_construction
        last_updated
        source
        originating_system
        accessory_dwelling_unit
        levels
        common_walls
        construction_materials
        basement
        foundation_details
        power_production_type
        roof
        sewer
        water_source
        irrigation_water_rights
        media_url
        is_auto_approve
        showing_request_deadline
        deadline_start_time
        created_at
        updated_at
        insert_uuid
        listing_agent {
          id
          first_name
          last_name
          email_address
          cell_phone
          logo
          brokerage
          realtor_number
          is_agent
          is_test_account
          validated
        }
        seller {
          id
          first_name
          last_name
          email_address
          cell_phone
          logo
          brokerage
          realtor_number
          is_agent
          is_test_account
          validated
        }
      }
      client {
        id
        first_name
        last_name
        email_address
        cell_phone
        logo
        brokerage
        realtor_number
        is_agent
        is_test_account
        validated
      }
      media_url
      seen_by_client
      active_for_client
      insert_uuid
      client_notes
      client_notes_updated_at
    }
  }
`;
export const onPropertyRecordsCreatedForClient = /* GraphQL */ `
  subscription OnPropertyRecordsCreatedForClient($client_id: Int!) {
    onPropertyRecordsCreatedForClient(client_id: $client_id) {
      property_listing_id
      property_of_interest_id
      client_id
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser($id: Int!) {
    onUpdateUser(id: $id) {
      id
      first_name
      last_name
      email_address
      address
      city
      state
      zip
      cell_phone
      cognito_sub
      cognito_identity
      time_zone
      subscription_id
      title
      logo
      brokerage
      realtor_number
      agent_id
      agent_notes
      is_agent
      validated
      onboarding_complete
      created_at
      updated_at
      push_token
      operating_system
      os_version
      insert_uuid
      is_test_account
      locked_out
      active_tour {
        id
        name
        status
        start_time
        end_time
        custom_start_name
        address_str
        latitude
        longitude
        client_id
        agent_id
        current_tour_stop_id
        current_tour_stop {
          id
          order
          duration
          notify_before
          notify_listing_agent
          notify_seller
          notify_after
          request_sent
          showing_request_required
          next_up_sent
          next_up_sent_by
          have_left_sent
          have_left_sent_by
          est_drive_duration
          est_drive_str
          comments
          client_interested
          start_time
          status
          tour_id
          property_of_interest_id
          last_request_sent_by_user_id
          created_at
          updated_at
          insert_uuid
          is_active
          property_of_interest {
            id
            property_listing_id
            client_id
            status
            notes
            created_at
            updated_at
            property_listing {
              id
              listing_agent_id
              seller_id
              created_by_user_id
              listing_id
              listing_key
              address
              city
              county
              state
              zip
              subdivision_name
              zoning
              latitude
              longitude
              parcel_number
              additional_parcels
              is_custom_listing
              listing_price
              association_fee
              association_fee_frequency
              on_market_date
              bedrooms
              bathrooms
              bathrooms_full
              square_feet
              square_feet_source
              lot_size
              year_built
              property_sub_type
              status
              description
              rented
              in_association
              community_features
              short_term_rental_permit_issued
              elementary_school
              middle_or_junior_school
              high_school
              tax_annual_amount
              tax_year
              tax_lot
              tax_map_number
              potential_tax_liability
              assessment
              senior_community
              appliances
              cooling
              heating
              fireplace_features
              flooring
              interior_features
              rooms
              window_features
              security_features
              architectural_style
              lot_features
              garage
              garage_spaces
              parking_features
              road_surface_types
              view
              horse_property
              new_construction
              last_updated
              source
              originating_system
              accessory_dwelling_unit
              levels
              common_walls
              construction_materials
              basement
              foundation_details
              power_production_type
              roof
              sewer
              water_source
              irrigation_water_rights
              media_url
              is_auto_approve
              showing_request_deadline
              deadline_start_time
              created_at
              updated_at
              insert_uuid
            }
            client {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
            media_url
            seen_by_client
            active_for_client
            insert_uuid
            client_notes
            client_notes_updated_at
          }
        }
        created_at
        updated_at
        insert_uuid
        client {
          id
          first_name
          last_name
          email_address
          cell_phone
          logo
          brokerage
          realtor_number
          is_agent
          is_test_account
          validated
        }
        stops {
          id
          order
          duration
          notify_before
          notify_listing_agent
          notify_seller
          notify_after
          request_sent
          showing_request_required
          next_up_sent
          next_up_sent_by
          have_left_sent
          have_left_sent_by
          est_drive_duration
          est_drive_str
          comments
          client_interested
          start_time
          status
          tour_id
          property_of_interest_id
          last_request_sent_by_user_id
          created_at
          updated_at
          insert_uuid
          is_active
          property_of_interest {
            id
            property_listing_id
            client_id
            status
            notes
            created_at
            updated_at
            property_listing {
              id
              listing_agent_id
              seller_id
              created_by_user_id
              listing_id
              listing_key
              address
              city
              county
              state
              zip
              subdivision_name
              zoning
              latitude
              longitude
              parcel_number
              additional_parcels
              is_custom_listing
              listing_price
              association_fee
              association_fee_frequency
              on_market_date
              bedrooms
              bathrooms
              bathrooms_full
              square_feet
              square_feet_source
              lot_size
              year_built
              property_sub_type
              status
              description
              rented
              in_association
              community_features
              short_term_rental_permit_issued
              elementary_school
              middle_or_junior_school
              high_school
              tax_annual_amount
              tax_year
              tax_lot
              tax_map_number
              potential_tax_liability
              assessment
              senior_community
              appliances
              cooling
              heating
              fireplace_features
              flooring
              interior_features
              rooms
              window_features
              security_features
              architectural_style
              lot_features
              garage
              garage_spaces
              parking_features
              road_surface_types
              view
              horse_property
              new_construction
              last_updated
              source
              originating_system
              accessory_dwelling_unit
              levels
              common_walls
              construction_materials
              basement
              foundation_details
              power_production_type
              roof
              sewer
              water_source
              irrigation_water_rights
              media_url
              is_auto_approve
              showing_request_deadline
              deadline_start_time
              created_at
              updated_at
              insert_uuid
            }
            client {
              id
              first_name
              last_name
              email_address
              cell_phone
              logo
              brokerage
              realtor_number
              is_agent
              is_test_account
              validated
            }
            media_url
            seen_by_client
            active_for_client
            insert_uuid
            client_notes
            client_notes_updated_at
          }
        }
        seen_by_client
        manually_ordered_showings
        is_behalf_of_buying_agent
      }
      agent_subscription {
        is_active
        is_manual
        original_order_id
        purchase_state
        expires_at
        canceled_at
      }
      requested_agent_id
      agent_request_seen
      is_free_version_account
      is_used_free_trial
    }
  }
`;
